### ISSUE TITLE
Handle string with binary format

### ISSUE THREAD

**Issue by Nokitoo** [Wizcorp/megadata#20]
Is there any specific reason why strings don't work with binary format ?

**Comment by stelcheck** [comment]
Because it was not implemented :)

It was built to deal with fixed-length messages; we could, in that spirit, add a fixed-length string type if needed. Going further than that would be overkill I think, however; we might as well integrate with Protobuf, Avro, etc instead if we wish to deal with serialization/deserialization of more complex datatypes.

I'll close the issue for now, but please feel free to re-open if you have any follow-up questions.
